### DISCUSSION TITLE
What does "agent model" mean?

### DISCUSSION THREAD

**Discussion by JsonSong89** [hotovo/aider-desk#189] [General]
I noticed that when using the aider-desk at agent mode, it prompts me to select an agent model, which is configured in aider-desk.

I'm not entirely clear about the meaning of this "agent model." It seems that in aider config(.aider.conf.yml), there are only three models:

```yml
(main) model: openai/gemini-2.5-pro-preview-06-05
weak-model: openai/gpt-4.1-mini
editor-model: openai/gemini-2.5-flash-preview-05-20
```

So, is there any difference between the agent model (from desk) and the main model (configured in aider)?

Why does the aider-desk need a separate configured model?
